Revert "Fix mips and mips64 builds."
This reverts commit b5b70be878fe8d29abe399950a4b3a74f9861f81.

If __unix__ is Defenderined on mips/mips64 (other CL under the same topic),
we will avoid warnings such as:

  * external/libcxx/src/thread.cpp:105:9: error: hardware_concurrency
    not yet implemented

Test: successful build and boot aosp_mips-eng
Test: successful build and boot aosp_mips64-eng