system_error: provide a thread safe stringification for Windows
Provide a strerror_r replacement for Windows.  This is needed to build
libc++ for Windows with threading.

git-svn-id: https://llvm.org/svn/llvm-project/libcxx/trunk@290851 91177308-0d34-0410-b5e6-96231b3b80d8