Revert "Revert "Turn off extern templates for most uses.""
The bionic tests on x86_64 are very unhappy about this:

external/gtest/include/gtest/gtest-printers.h:245: error: undefined reference to 'std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(__float128)'
external/gtest/include/gtest/gtest-printers.h:245: error: undefined reference to 'std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(__float128)'
external/gtest/include/gtest/gtest-printers.h:245: error: undefined reference to 'std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(__float128)'
external/gtest/include/gtest/gtest-printers.h:245: error: undefined reference to 'std::__1::basic_ostream<char, std::__1::char_traits<char> >::operator<<(__float128)'

I'll investigate tomorrow, but for now it's easiest to just revert.

This reverts commit 98c4e404ca8c524c54b4e7ede97b807355422b53.
Change-Id: I4c4e83be2ca465069734c54f4dcfa539916d35e4